[package]
name = "inline_hook_test"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.56", features = [
  "Win32_Foundation",
  "Win32_Storage",
  "Win32_Storage_FileSystem",
  "Win32_Security",
] }
